---
- name: Collect authorized_keys from all users (including system and root)
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Get list of users and home directories from /etc/passwd
      command: 'awk -F: ''{print $1":"$6}'' /etc/passwd'
      register: passwd_entries

    - name: Set fact with user/home pairs
      set_fact:
        users_info: "{{ passwd_entries.stdout_lines | map('split', ':') | list }}"

    - name: Check if authorized_keys exists
      stat:
        path: "{{ item[1] }}/.ssh/authorized_keys"
      register: auth_keys_stat
      loop: "{{ users_info }}"
      loop_control:
        label: "{{ item[0] }}"

    - name: Fetch existing authorized_keys files
      fetch:
        src: "{{ item.item[1] }}/.ssh/authorized_keys"
        dest: "~/tmp/collected_keys/{{ inventory_hostname }}/{{ item.item[0] }}_authorized_keys"
        flat: yes
      when: item.stat.exists
      loop: "{{ auth_keys_stat.results }}"
      loop_control:
        label: "{{ item.item[0] }}"
