---
- hosts: all
  become: true
  tasks:

#  - name: install apache2 package
#    ansible.builtin.apt:
#      name: 
#        - apache2
#        - libapache2-mod-php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

#  - name: install apache2 package
#    ansible.builtin.dnf:
#      name: 
#        - httpd
#        - php
#      use_backend: dnf4
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Fedora"

  - name: install apache2 package
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

